In [1]:
import numpy as np
import sklearn.datasets as ds
import numpy as np
large_array, _ = ds.make_gaussian_quantiles(n_samples=10000, n_features=1, random_state=42)
large_array= large_array.reshape((10000,))
a = np.array(ds.load_iris().data)


## 1. Efficiency of numpy operations
large_array is generated with dummy data. You do not have to understand how it's done.

a. Check the dtype and shape of `large_array`

In [ ]:
#SOLUTION_START
print(f'The shape of large_array is {large_array.shape} and its dtype is {large_array.dtype}')
#SOLUTION_END

b. Create a for-loop in which you calculate the power of 2 for each element. `%%timeit` is  placed at the beginning of the cell. By doing this, Jupiter will do several runs and measure the speed of the operation. The result is shown below the cell. Run the cell and wait for the result. Look how long running the for-loop takes.

In [ ]:
%%timeit
#SOLUTION_START
for e in large_array:
    e**2
#SOLUTION_END

c. In the cell below, do the same with the Ufuncs functionality instead of a for-loop. Use %%timeit again. Compare the duration. How big is the difference?

In [ ]:
%%timeit
#SOLUTION_START
large_array**2
#SOLUTION_END

<div style="border: 2px solid red; padding: 10px; border-radius: 5px; background-color: #f8d7da; color: #721c24;">
<strong>! </strong>As you can see for yourself there is a big difference.
From now on, where possible, you have to use UFuncs instead of for-loops. The code is more lean and will be excecuted more efficiently. During evaluations for-loops will influence your score negatively and are even not allowed in most cases..</div>


## 2. Using UFuncs
Us UFuncs to perform the following operations on array a.\
a. From array a, calculate the square root of each element.\
b. From array a, round the first column to the nearest integer.\
c. From array a, add 1 to every value of the first row.


In [3]:
#SOLUTION_START
print(f'a. The square root of each element in a is {np.sqrt(a)}')
print(f'b. The first column rounded to the nearest integer is {np.round(a[:,0])}')
print(f'c. The first row with 1 added to every element is {a[0,:]+1}')
#SOLUTION_END

a. The square root of each element in a is [[2.25831796 1.87082869 1.18321596 0.4472136 ]
 [2.21359436 1.73205081 1.18321596 0.4472136 ]
 [2.16794834 1.78885438 1.14017543 0.4472136 ]
 [2.14476106 1.76068169 1.22474487 0.4472136 ]
 [2.23606798 1.8973666  1.18321596 0.4472136 ]
 [2.32379001 1.97484177 1.30384048 0.63245553]
 [2.14476106 1.84390889 1.18321596 0.54772256]
 [2.23606798 1.84390889 1.22474487 0.4472136 ]
 [2.0976177  1.70293864 1.18321596 0.4472136 ]
 [2.21359436 1.76068169 1.22474487 0.31622777]
 [2.32379001 1.92353841 1.22474487 0.4472136 ]
 [2.19089023 1.84390889 1.26491106 0.4472136 ]
 [2.19089023 1.73205081 1.18321596 0.31622777]
 [2.07364414 1.73205081 1.04880885 0.31622777]
 [2.40831892 2.         1.09544512 0.4472136 ]
 [2.38746728 2.0976177  1.22474487 0.63245553]
 [2.32379001 1.97484177 1.14017543 0.63245553]
 [2.25831796 1.87082869 1.18321596 0.54772256]
 [2.38746728 1.94935887 1.30384048 0.54772256]
 [2.25831796 1.94935887 1.22474487 0.54772256]
 [2.32379001 1.84