In [1]:
import numpy as np
import sklearn.datasets as ds
import numpy as np
b, _ = ds.make_gaussian_quantiles(n_samples=10000, n_features=4, random_state=42)
a= np.array(ds.load_iris().data)[0:100,:]
c = np.arange(1,5)
d= a[10:14,0].reshape(4,1)


## 1. Broadcasting
a,b,c and d arre generated with dummy data. You do not have to understand how it's done.\
a. Print the array a, b, c, and d.\
b. Print the number of dimensions of a, b, c, and d.\
c. print the shape of a, b, c, and d.\
_It is important to understand the shape of the arrays when broadcasting. Make sure you understand the shape of the arrays before you start the next steps._


In [6]:
print(a, b, c, d)
print(a.ndim, b.ndim, c.ndim, d.ndim)
print(a.shape, b.shape, d.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

c. Pick the first 100 rows of b. Add array a to these rows.

In [7]:
b[:100] + a

array([[ 6.04469887,  4.90606928, -0.47641785, -2.14179744],
       [ 4.23955263,  2.2205438 ,  1.90950138, -0.84046731],
       [ 3.08973688,  3.95318995,  0.21798221, -0.13866905],
       [ 5.49808069,  2.83028969,  4.79590446,  0.75318059],
       [ 4.13196822,  2.18893239,  1.64610642,  1.31636145],
       [ 5.43302331,  5.24694124,  2.47402277,  0.3925192 ],
       [ 4.25434634,  4.17185049,  2.23173314,  0.1095143 ],
       [ 5.59891272,  3.58074389,  0.03707179,  0.70695554],
       [ 6.38782091,  2.28860607,  1.19814148, -0.81857062],
       [ 6.15522625,  5.0686541 ,  1.69937992, -0.74562849],
       [ 5.03686835,  4.554402  ,  1.84121584,  1.70027461],
       [ 4.52533987,  4.58758947,  1.06016367,  1.87701268],
       [ 3.72924562,  3.96609286,  1.96028089, -1.88629061],
       [ 3.39824847,  4.15103014,  1.31202681,  0.4425234 ],
       [ 6.55408581,  3.84168039,  3.06803292,  0.19608749],
       [ 7.84300705,  3.93023554,  1.65875605,  1.55600667],
       [ 4.55355563,  3.

d. For each row in  array a, calculate the sum of the power of the first column and the power of the second column.

In [8]:
a[:,0] ** 2 + a[:,1] ** 2

array([38.26, 33.01, 32.33, 30.77, 37.96, 44.37, 32.72, 36.56, 27.77,
       33.62, 42.85, 34.6 , 32.04, 27.49, 49.64, 51.85, 44.37, 38.26,
       46.93, 40.45, 40.72, 39.7 , 34.12, 36.9 , 34.6 , 34.  , 36.56,
       39.29, 38.6 , 32.33, 32.65, 40.72, 43.85, 47.89, 33.62, 35.24,
       42.5 , 36.97, 28.36, 37.57, 37.25, 25.54, 29.6 , 37.25, 40.45,
       32.04, 40.45, 31.4 , 41.78, 35.89, 59.24, 51.2 , 57.22, 35.54,
       50.09, 40.33, 50.58, 29.77, 51.97, 34.33, 29.  , 43.81, 40.84,
       45.62, 39.77, 54.5 , 40.36, 40.93, 43.28, 37.61, 45.05, 45.05,
       45.94, 45.05, 49.37, 52.56, 54.08, 53.89, 44.41, 39.25, 36.01,
       36.01, 40.93, 43.29, 38.16, 47.56, 54.5 , 44.98, 40.36, 36.5 ,
       37.01, 46.21, 40.4 , 30.29, 38.65, 41.49, 40.9 , 46.85, 32.26,
       40.33])

e. You are going to multiply array a with array c. Before doing, predict the shape of the resulting array and results of the first row based on __the rules of broadcasting__.\
f. Now, multiply array a with array c and compare the result with your prediction.

In [11]:
print(a.shape)
print(c.shape)
print(c)
# 5.1, 7, 4.2, 0.8

print((a * c)[0])

(100, 4)
(4,)
[1 2 3 4]
[5.1 7.  4.2 0.8]


First rule 1 is applied to array c. The shape of c is padded to (1,4) because it had less dimensions than a.
`[1,2,3,4] -> [[1,2,3,4]]` 

Then, rule 2 is applied to c. The shape of c is stretched to (100,4) to match the shape of a.
`[[1,2,3,4]] -> [[1,2,3,4],[1,2,3,4],...,[1,2,3,4]]`

Finally, the two arrays are multiplied element-wise.   

g. Now multiply array a with array d. Before doing, predict the shape of the resulting array and results of the first row based on __the rules of broadcasting__.


In [13]:
print(a.shape)
print(d.shape)
a * d

(100, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (100,4) (4,1) 

Rule 1: the number of dimensions is the same for both arrays. Padding not applied.\
Rule 2: The shape of d is stretched from (4,1) to (4,4) to match the shape of a.\
Rule 3: The dimensions of the arrays differ. An error is raised.\

h. Now multiply c with. d. Before doing, predict the shape of the resulting array and results of the first row based on __the rules of broadcasting__.

In [20]:
print(c.shape)
print(d.shape)

print(c)
print(d)

cd = c * d
print(cd.shape)
# 5.4, 10.8, 16.2, 21.6
print(cd[0])

(4,)
(4, 1)
[1 2 3 4]
[[5.4]
 [4.8]
 [4.8]
 [4.3]]
(4, 4)
[ 5.4 10.8 16.2 21.6]


Rule 1:shape c (4,) becomes (1,4) to match the shape of d (4,1)\
Rule 2: c is stretched to (4,4). d (4,1) is stretched to (4,4) to match the shape of c.\
Rule 3: The two arrays are multiplied element-wise.

i. For dataset a, normalize the data by calculating the z-score for each column. This way you can compare the columns of the dataset.\
*In case you don't remember, the formula for the z-score is: x-mean/std.*

In [26]:
mean = a.mean(axis=0)
std = a.std(axis=0)
print((a - mean)/std)

[[-5.81065904e-01  8.41837140e-01 -1.01297765e+00 -1.04211089e+00]
 [-8.94308978e-01 -2.07835104e-01 -1.01297765e+00 -1.04211089e+00]
 [-1.20755205e+00  2.12033793e-01 -1.08231219e+00 -1.04211089e+00]
 [-1.36417359e+00  2.09934449e-03 -9.43643106e-01 -1.04211089e+00]
 [-7.37687441e-01  1.05177159e+00 -1.01297765e+00 -1.04211089e+00]
 [-1.11201292e-01  1.68157493e+00 -8.04974023e-01 -6.86441647e-01]
 [-1.36417359e+00  6.31902691e-01 -1.01297765e+00 -8.64276271e-01]
 [-7.37687441e-01  6.31902691e-01 -9.43643106e-01 -1.04211089e+00]
 [-1.67741667e+00 -4.17769553e-01 -1.01297765e+00 -1.04211089e+00]
 [-8.94308978e-01  2.09934449e-03 -9.43643106e-01 -1.21994552e+00]
 [-1.11201292e-01  1.26170604e+00 -9.43643106e-01 -1.04211089e+00]
 [-1.05093052e+00  6.31902691e-01 -8.74308565e-01 -1.04211089e+00]
 [-1.05093052e+00 -2.07835104e-01 -1.01297765e+00 -1.21994552e+00]
 [-1.83403820e+00 -2.07835104e-01 -1.22098127e+00 -1.21994552e+00]
 [ 5.15284858e-01  1.89150938e+00 -1.15164673e+00 -1.04211089e