In [4]:
import numpy as np
import sklearn.datasets as ds
import numpy as np
large_array, _ = ds.make_gaussian_quantiles(n_samples=10000, n_features=1, random_state=42)
large_array= large_array.reshape((10000,))
a = np.array(ds.load_iris().data)
print(f"The shape of large_array is {large_array.shape} and its dtype is {large_array.dtype}")

The shape of large_array is (10000,) and its dtype is float64


## 2. Aggregations
large_array is generated with dummy data. You do not have to understand how it's done. You can consult the shape and dtype of large_array in the output above.\
a. Calculate the mean of array a.\
b. Calculate the sum of all the columns in a.\
c. Calculate the product of all the rows in a.



In [2]:
#SOLUTION_START
print(f'a. The square root of each element in a is {np.sqrt(a)}')
print(f'b. The first column rounded to the nearest integer is {np.round(a[:,0])}')
print(f'c. The first row with 1 added to every element is {a[0,:]+1}')
#SOLUTION_END

a. The square root of each element in a is [[2.25831796 1.87082869 1.18321596 0.4472136 ]
 [2.21359436 1.73205081 1.18321596 0.4472136 ]
 [2.16794834 1.78885438 1.14017543 0.4472136 ]
 [2.14476106 1.76068169 1.22474487 0.4472136 ]
 [2.23606798 1.8973666  1.18321596 0.4472136 ]
 [2.32379001 1.97484177 1.30384048 0.63245553]
 [2.14476106 1.84390889 1.18321596 0.54772256]
 [2.23606798 1.84390889 1.22474487 0.4472136 ]
 [2.0976177  1.70293864 1.18321596 0.4472136 ]
 [2.21359436 1.76068169 1.22474487 0.31622777]
 [2.32379001 1.92353841 1.22474487 0.4472136 ]
 [2.19089023 1.84390889 1.26491106 0.4472136 ]
 [2.19089023 1.73205081 1.18321596 0.31622777]
 [2.07364414 1.73205081 1.04880885 0.31622777]
 [2.40831892 2.         1.09544512 0.4472136 ]
 [2.38746728 2.0976177  1.22474487 0.63245553]
 [2.32379001 1.97484177 1.14017543 0.63245553]
 [2.25831796 1.87082869 1.18321596 0.54772256]
 [2.38746728 1.94935887 1.30384048 0.54772256]
 [2.25831796 1.94935887 1.22474487 0.54772256]
 [2.32379001 1.84

d. Calculate the standard deviation of the first column in a by calculation the standard deviation of every column of array a and then selecting the first element of the resulting array.

In [3]:
#SOLUTION_START
a.std(axis=0)[0]
%timeit a.std(axis=0)[0]
#SOLUTION_END

0.8253012917851409

41.9 μs ± 2.31 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)



e. Calculate the standard deviation of the first column in a by selecting the first column and then calculating the standard deviation.

In [4]:
#SOLUTION_START
a[:,0].std()
%timeit a[:,0].std()
#SOLUTION_END

0.8253012917851409

29.3 μs ± 1.07 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


f. Compare the time it takes to calculate the standard deviation of the first column in a using the two methods above. Which method is faster? Why

In [8]:
#SOLUTION_START
%timeit a.std(axis=0)[0]
%timeit a[:,0].std()
#SOLUTION_END

42.1 μs ± 10.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
27.6 μs ± 3.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


This is another example where chosing the right method can make a big difference in performance. Chosing an efficient solution will be taken into account when evaluating. 